resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml

images:
  - name: alpine
    newTag: '3.23'
  - name: lab-vpn
    newName: ghcr.io/bacchus-snu/lab-vpn
    digest: sha256:38876c845d270b2c3d1957db122f4647ebb8f77de48bccf4902372f78014e99f
