resources:
  - resources.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/instance: cloudflared
    includeSelectors: true

images:
  - name: cloudflared
    newName: cloudflare/cloudflared
    newTag: 2025.11.1
