---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: bacchus-sgs-dev
  name: bacchus-sgs-dev-prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: bacchus-sgs-dev
  name: bacchus-sgs-dev-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # use ClusterRole from kube-prometheus-stack
  name: dashboard-kube-prometheus-prometheus
subjects:
  - kind: ServiceAccount
    name: bacchus-sgs-dev-prometheus
    namespace: bacchus-sgs-dev
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  namespace: bacchus-sgs-dev
  name: bacchus-sgs-dev-prometheus
spec:
  version: v3.1.0
  scrapeInterval: 1m
  evaluationInterval: 1m
  scrapeConfigSelector:
    matchLabels:
      app.kubernetes.io/name: bacchus-sgs-monitoring-dev
      app.kubernetes.io/instance: bacchus-sgs-monitoring-dev
  ruleSelector:
    matchLabels:
      app.kubernetes.io/name: bacchus-sgs-monitoring-dev
      app.kubernetes.io/instance: bacchus-sgs-monitoring-dev
  alerting:
    alertmanagers:
      - apiVersion: v2
        name: alertmanager-operated
        port: web
  serviceAccountName: bacchus-sgs-dev-prometheus
  externalUrl: https://sgs-dev-dashboard.internal.bacchus.io/prometheus
  routePrefix: /
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  enableFeatures:
    # sort_by_label
    - promql-experimental-functions
  retention: 30d
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOncePod
        resources:
          requests:
            storage: 100Gi
